name: feastify
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  geolocator: ^13.0.2
  http: ^1.3.0
  animated_text_kit: ^4.2.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - images/hotelImagesFolder/
    - images/LongRowImages/
    - images/IndividualHotel/TGI/
    - images/IndividualHotel/OBE/
    - images/IndividualHotel/TajPalace/
    - images/IndividualHotel/LE/
    - images/Offergifts/
    - images/applogos/
    - images/



  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Fuemen
      fonts:
        - asset: assets/fonts/Fuemen.ttf
    - family: KumarOne
      fonts:
        - asset: assets/fonts/KumarOne.ttf


  uses-material-design: true

