name: attendance_tracking
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  iconsax: ^0.0.8
  pinput: ^5.0.1
  intl: ^0.20.2
  lottie: ^3.3.1
  slide_to_act: ^2.0.2
  google_fonts: ^6.2.1
  iconsax_flutter: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0




flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: PoppinsLight
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf

    - family: PoppinsBold
      fonts:
        -  asset: fonts/Poppins-Bold.ttf

    - family: Outfit
      fonts:
        - asset: fonts/Outfit.ttf

    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 900
    - family: AfacadFlux
      fonts:
        - asset: fonts/AfacadFlux-Regular.ttf
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Regular.ttf


  assets:
    - assets/blueSuccess.json
    - images/PasswordValidation/
    #ukesh
    - images/starting_images/



  uses-material-design: true
